import { Router } from 'express';
import { store, persist, id, isoDay } from '../store.js';
import { auth } from '../middleware/auth.js';
const r = Router(); r.use(auth);
const mine = (req) => store.problems.filter(p => p.userId === req.user.id);
const revisions = (req) => store.revisions.filter(x => x.userId === req.user.id);
const solvedDays = (req) => [...new Set(mine(req).filter(p => p.status === 'solved' && p.solvedAt).map(p => p.solvedAt.slice(0,10)))].sort();
function streak(days) { let n=0, d=new Date(); const set=new Set(days); if (!set.has(isoDay(d))) d.setDate(d.getDate()-1); while(set.has(isoDay(d))){n++;d.setDate(d.getDate()-1)} return n; }
function longest(days){let best=0,run=0,prev=null;for(const day of days){const d=new Date(`${day}T00:00:00Z`);if(prev&&d-prev===86400000)run++;else run=1;best=Math.max(best,run);prev=d}return best;}
r.get('/dashboard',(req,res)=>{const ps=mine(req), today=isoDay(), week=new Date(); week.setDate(week.getDate()-6); week.setHours(0,0,0,0); const rev=revisions(req).filter(x=>!x.completedAt&&x.dueDate<=today).length;const days=solvedDays(req);const daily=Number(req.user.dailyGoal||5);const weekGoal=Number(req.user.weeklyGoal||20);const weekSolved=ps.filter(p=>p.status==='solved'&&p.solvedAt&&new Date(p.solvedAt)>=week).length; const activity=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);const day=isoDay(d);return {day,label:d.toLocaleDateString('en',{weekday:'short'}),solved:ps.filter(p=>p.status==='solved'&&p.solvedAt?.slice(0,10)===day).length}}); const topics={};ps.forEach(p=>{const t=p.topic||'Uncategorized';topics[t]??={topic:t,total:0,solved:0};topics[t].total++;if(p.status==='solved')topics[t].solved++}); res.json({stats:{solved:ps.filter(p=>p.status==='solved').length,thisWeek:weekSolved,streak:streak(days),longestStreak:longest(days),due:rev},today:{solved:activity[6].solved,goal:daily,remaining:Math.max(0,daily-activity[6].solved)},week:{solved:weekSolved,goal:weekGoal},activity,recent:ps.filter(p=>p.status==='solved').sort((a,b)=>b.solvedAt.localeCompare(a.solvedAt)).slice(0,6),topics:Object.values(topics).sort((a,b)=>a.solved/(a.total||1)-b.solved/(b.total||1)).slice(0,5),due:revisions(req).filter(x=>!x.completedAt&&x.dueDate<=today).map(x=>({...x,problem:ps.find(p=>p.id===x.problemId)})).filter(x=>x.problem)});});
r.get('/problems',(req,res)=>res.json({problems:mine(req).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}));
r.get('/topics',(req,res)=>{const topics={};for(const p of mine(req)){const name=p.topic||'Uncategorized';topics[name]??={name,total:0,solved:0,lastSolved:null};topics[name].total++;if(p.status==='solved'){topics[name].solved++;if(!topics[name].lastSolved||p.solvedAt>topics[name].lastSolved)topics[name].lastSolved=p.solvedAt}}res.json({topics:Object.values(topics).map(t=>({...t,unsolved:t.total-t.solved,completion:t.total?Math.round(t.solved*100/t.total):0})).sort((a,b)=>a.name.localeCompare(b.name))})});
r.post('/problems',(req,res)=>{const {title,platform='',url='',topic='',difficulty='Medium',notes=''}=req.body;if(!title?.trim())return res.status(400).json({message:'Please enter a problem title.'});if(!['Easy','Medium','Hard'].includes(difficulty))return res.status(400).json({message:'Choose a valid difficulty.'});if(url&&!/^https?:\/\//i.test(url))return res.status(400).json({message:'Problem URL must start with http:// or https://.'});const p={id:id(),userId:req.user.id,title:title.trim(),platform:platform.trim(),url:url.trim(),topic:topic.trim(),difficulty,status:'todo',notes:notes.trim(),createdAt:new Date().toISOString(),solvedAt:null};store.problems.push(p);persist();res.status(201).json({problem:p});});
r.patch('/problems/:id',(req,res)=>{const p=mine(req).find(x=>x.id===req.params.id);if(!p)return res.status(404).json({message:'Problem not found.'});const b=req.body;if(b.title!==undefined&&!b.title.trim())return res.status(400).json({message:'Please enter a problem title.'});for(const k of ['title','platform','url','topic','difficulty','notes','status'])if(b[k]!==undefined)p[k]=typeof b[k]==='string'?b[k].trim():b[k];if(b.status!==undefined&&!['todo','attempted','solved'].includes(b.status))return res.status(400).json({message:'Choose a valid status.'});if(b.status==='solved'&&p.status==='solved'&&p.solvedAt){}else if(b.status==='solved'){p.solvedAt=new Date().toISOString();for(const [i,days] of [1,3,7,21].entries())store.revisions.push({id:id(),userId:req.user.id,problemId:p.id,sequence:i+1,dueDate:isoDay(Date.now()+days*86400000),completedAt:null});}else if(b.status&&b.status!=='solved')p.solvedAt=null;p.updatedAt=new Date().toISOString();persist();res.json({problem:p});});
r.delete('/problems/:id',(req,res)=>{const i=store.problems.findIndex(p=>p.userId===req.user.id&&p.id===req.params.id);if(i<0)return res.status(404).json({message:'Problem not found.'});const [p]=store.problems.splice(i,1);store.revisions=store.revisions.filter(x=>x.problemId!==p.id);persist();res.sendStatus(204);});
r.get('/revisions',(req,res)=>{const ps=mine(req);res.json({revisions:revisions(req).map(x=>({...x,problem:ps.find(p=>p.id===x.problemId)})).filter(x=>x.problem).sort((a,b)=>a.dueDate.localeCompare(b.dueDate))});});
r.post('/revisions/:id/complete',(req,res)=>{const rev=revisions(req).find(x=>x.id===req.params.id);if(!rev)return res.status(404).json({message:'Revision not found.'});if(rev.completedAt)return res.status(409).json({message:'This revision is already complete.'});rev.completedAt=new Date().toISOString();persist();res.json({revision:rev});});
r.get('/goals',(req,res)=>res.json({goals:{daily:Number(req.user.dailyGoal||5),weekly:Number(req.user.weeklyGoal||20)}}));
r.put('/goals',(req,res)=>{const daily=Number(req.body.daily),weekly=Number(req.body.weekly);if(!Number.isInteger(daily)||daily<1||daily>100||!Number.isInteger(weekly)||weekly<1||weekly>500)return res.status(400).json({message:'Goals must be positive whole numbers within the allowed range.'});req.user.dailyGoal=daily;req.user.weeklyGoal=weekly;persist();res.json({goals:{daily,weekly}})});
r.get('/analytics',(req,res)=>{const ps=mine(req), solved=ps.filter(p=>p.status==='solved'),topics={};const range=Math.max(7,Math.min(90,Number(req.query.days)||30));const chart=Array.from({length:range},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(range-1-i));const day=isoDay(d);return {day,label:day.slice(5),solved:solved.filter(p=>p.solvedAt?.slice(0,10)===day).length}});for(const p of ps){const k=p.topic||'Uncategorized';topics[k]??={name:k,total:0,solved:0};topics[k].total++;if(p.status==='solved')topics[k].solved++}const rv=revisions(req);res.json({total:solved.length,difficulty:['Easy','Medium','Hard'].map(name=>({name,value:solved.filter(p=>p.difficulty===name).length})),topics:Object.values(topics),platforms:Object.entries(solved.reduce((a,p)=>(a[p.platform||'Unspecified']=(a[p.platform||'Unspecified']||0)+1,a),{})).map(([name,value])=>({name,value})),chart,revisions:{completed:rv.filter(x=>x.completedAt).length,pending:rv.filter(x=>!x.completedAt).length},activeDays:solvedDays(req).length});});
export default r;
